### ISSUE TITLE
is it possible le to see matplotlib plots

### ISSUE THREAD

**Issue by Sandy4321** [kmaork/madbg#38]
is it possible le to see matplotlib plots

**Comment by kmaork** [comment]
Please elaborate. Are you debugging a remote machine?

**Comment by kmaork** [comment]
Madbg does not provide UI forwarding capabilities, consider connecting to your remote machine using `ssh -X` or any other remote connection that supports x forwarding, and then using `madbg` to display anything you want

**Comment by Sandy4321** [comment]
do you have some video or another clear example how to do it ?

**Comment by kmaork** [comment]
If you can, connect to the remote machine using `ssh -X` and run the debogged program in that session. Then connect the debugger however you want, and use normal matplotlib functions in the debugger to view plots.
