### ISSUE TITLE
abort: no module named 'madbg'

### ISSUE THREAD

**Issue by jaraco** [kmaork/madbg#49]
While attempting to use `madbg`, I have a stuck Python process present before even installing madbg. I installed madbg into a virtualenv and tried to attach to that process, but that caused an error in the attached process:

```
abort: no module named 'madbg'
```

And led to a TimeoutError in the client.

It's not at all obvious from the README that the process to be attached requires that madbg be installed/present. It's sort-of implied by the presence of `madbg run` commands.

Ways this experience could be improved:

- In the README, declare that the attached process needs to have madbg installed/importable.
- Have the client inject the sys.path where madbg is installed (maybe not a good idea?).
- Provide explicit error handling during attachment if madbg is not importable.

**Comment by kmaork** [comment]
Thank you for the report and the suggestions! I'll update the README :) Closing in favor of #33
